name: adventuresmith_templates
description: Core template processing engine for Adventuresmith
version: 1.0.0
homepage: https://github.com/Adventuresmith/adventuresmith_templates
repository: https://github.com/Adventuresmith/adventuresmith_templates


environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  dart_dice_parser: ^5.1.4
  mustache_template: ^2.0.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.16.0
